/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Timeland_CONSTANTS_H
#define Timeland_CONSTANTS_H

#include "Timeland_types.h"

namespace timeland_thrift {

class TimelandConstants {
 public:
  TimelandConstants();

};

extern const TimelandConstants g_Timeland_constants;

} // namespace

#endif
