/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "Timeland_constants.h"

namespace timeland_thrift {

const TimelandConstants g_Timeland_constants;

TimelandConstants::TimelandConstants() {
}

} // namespace

